// go-next-tag is a simple command-line application for calculating the next `major-minor` or `semantic` version given a
// tag.
package main

import (
	"fmt"
	"os"

	versioning "github.com/idelchi/go-next-tag/internal/versioning"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	cfg, err := parseFlags()
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing flags: %v\n", err)

		os.Exit(1)
	}

	if err := cfg.Validate(); err != nil {
		fmt.Fprintf(os.Stderr, "validating configuration: %v\n", err)

		os.Exit(1)
	}

	nextTag, err := versioning.Next(cfg.Tag, cfg.Bump)
	if err != nil {
		fmt.Fprintf(os.Stderr, "calculating next tag: %v\n", err)

		os.Exit(1)
	}

	fmt.Println(cfg.Prefix + versioning.ToFormat(nextTag, cfg.Format))
}
