workflow:
  rules:
    - when: always

include:
  - project: <company>/scsa-shared-tools/templates
    ref: feature/experiments
    file:
      - proxy.gitlab-ci.yml
      - registry.gitlab-ci.yml
      - tag.gitlab-ci.yml
      - kaniko-build.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always

stages:
  - quality
  - test
  - build
  - release

# Lint all files in the repository
lint:
  except:
    - tags
  stage: quality
  image: $DOCKER_REGISTRY_COMMON/style:latest
  script:
    - task lint

# Lint all go files in the repository
go:
  except:
    - tags
  stage: quality
  image: $DOCKER_REGISTRY_COMMON/go:latest
  script:
    - task go:lint

container:
  except:
    - tags
  stage: test
  extends: .kaniko-build
  variables:
    DOCKER_IMAGE: devenv
    DOCKER_TAG: $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA
    DOCKERFILE: Dockerfile
    DOCKER_REGISTRY: $DOCKER_REGISTRY_DUMPSTER
    DOCKER_IMAGE_ENV_VAR: DEVENV
    ARGS: >
      --build-arg GO_NEXT_TAG_VERSION=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

# Run the go test suite
test:
  except:
    - tags
  stage: test
  image: $DEVENV
  script:
    - go-next-tag $ARGS
  parallel:
    matrix:
      - ARGS: --bump=patch
      - ARGS: --bump=minor
      - ARGS: --bump=major
      - ARGS: --bump=patch --format semver
      - ARGS: --bump=minor --format semver
      - ARGS: --bump=major --format semver
  needs:
    - container

docker:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: $CI_COMMIT_TAG

    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        DOCKER_TAG: latest

    # TODO(Idelchi): MRs are being identified with the `branch-name`.
    # Should avoid that - check $CI_COMMIT_REF_NAME for MRs, and exclude using appropriate condition.

    - if: $CI_COMMIT_REF_NAME == "dev"
      variables:
        DOCKER_TAG: $CI_COMMIT_REF_NAME

    - when: on_success
      variables:
        DOCKER_TAG: 0.0-$CI_COMMIT_BRANCH
        EXTRA_ARGS: >
          --no-push
  extends: .kaniko-build
  variables:
    DOCKERFILE: Dockerfile
    DOCKER_IMAGE: go-next-tag
    DOCKER_IMAGE_ENV_VAR: go_next_tag
    DOCKER_REGISTRY: $DOCKER_REGISTRY_ART_COMMON
    DOCKER_REGISTRY_MIRRORS: >
      $DOCKER_REGISTRY_BIN_COMMON
    ARGS: >
      --build-arg GO_NEXT_TAG_VERSION=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

release:
  stage: release
  extends: .tag-and-push
