/*
go-next-tag is a simple command-line application for incrementing version tags.
It returns the next version based on the given version, format and bump strategy.

Usage:

	echo [version] | go-next-tag [flags] [version]

For full usage information, run `go-next-tag -h`.

`go-next-tag supports` configuration through environment variables starting with the prefix `GO_NEXT_TAG_`.
For example, to set the bump strategy, use `GO_NEXT_TAG_BUMP`.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/go-next-tag/internal/logic"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := logic.Run(version); err != nil {
		fmt.Fprintf(os.Stderr, "running the application: %v\n", err)

		os.Exit(1)
	}

	os.Exit(0)
}
