name: go-next-tag
on: [push, pull_request, workflow_dispatch]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  IMAGE: ${{ github.repository }}

jobs:
  verify:
    uses: idelchi/devenv/.github/workflows/devenv-actions.yml@dev
    with:
      image: idelchi/devenv:dev

  release:
    runs-on: ubuntu-22.04
    needs: [verify]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE }}:dev
# TODO(Idelchi): Handle release workflows.
# https://github.com/skills/release-based-workflow
# https://birtony.medium.com/setting-up-automated-release-workflow-with-github-actions-628dbca2446e
# https://rangle.io/blog/release-process-github-actions
